version: 'appveyor-t{build}'
image: Visual Studio 2017
configuration:
- Release
platform:
- x64
install:
- cmd: |-
    git submodule update --init --recursive
before_build:
- cmd: |-
    cd C:/projects
    git clone https://github.com/misson20000/libusbk.git
    cd libusbk/libusbk
    msbuild libusbK.sln /p:Configuration=Release,Platform=x64 /t:"lib\libusbK"
    cd C:/projects/twili/twib
    mkdir build
    cd build
    cmake --version
#- ps:	$blockRdp =	$true; iex ((new-object	net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
- cmd: |-
    cd C:/projects/twili/twib/build
    cmake .. -DLIBUSBK_LIBRARIES=C:/projects/libusbK/libusbK/bin/lib/x64/Release/libusbK.lib -DLIBUSBK_INCLUDE_DIRS=C:/projects/libusbK/libusbK/includes -DCMAKE_GENERATOR_PLATFORM=x64
build:
  project: c:/projects/twili/twib/build/twib.sln
  parallel: true
after_build:
- cmd: |-
    copy C:\projects\twili\twib\build\tool\Release\twib.exe C:\projects\twili\twib_win64.exe
    copy C:\projects\twili\twib\build\daemon\Release\twibd.exe C:\projects\twili\twibd_win64.exe
artifacts:
- path: twib_win64.exe
- path: twibd_win64.exe
deploy:
  description: 'describe this release'
  provider: GitHub
  auth_token:
    # secure: DzLSBd8C9af8pEBk+td3FnGySUJmMlpgE2QTRJk9gsaClLktgjEmeJLRfQwRp+Mr # m20k key
    secure: S/hibwHUTh6XJMB6iixGFBZBgng4QgtP7r9loKFxpvEKrl+cseji6jwc2RBW59yL # reswitchedteam key
  draft: true
  force_update: true
  on:
    APPVEYOR_REPO_TAG: true
