[package]
name = "twib"
version = "0.1.0"
authors = ["misson20000 <xenotoad@xenotoad.net>"]

[dependencies]
libusb = { path = "../../../../libusb-rs" }
getopts = "0.2"
byteorder = "1"
rand = "0.4"
prettytable-rs = "^0.6"
rmpv = "0.4.0"
mio = "0.6"
tokio = "0.1.7"
